version: '3'
services:
  apollo-gateway:
    build: ./gateway
    ports:
      - "4000:4000"
  servicea:
    ports:
      - "4001:4001"
    image: servicea
  serviceb:
    ports:
      - "4002:4002"
    image: serviceb
